# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Data Products Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout adsepra
      uses: actions/checkout@v3
      with:
        repository: ottensa/ad-sepra
        path: adsepra
        
    - name: Checkout sepdpc
      uses: actions/checkout@v3
      with:
        repository: ottensa/ad-sepra
        path: sepdpc
        
    - name: Checkout Data Product Definitions
      uses: actions/checkout@v3
      with:
        path: main
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install sepdpc
      run: |
        python -m pip install --upgrade pip
        pip install $GITHUB_WORKSPACE/adsepra
        pip install $GITHUB_WORKSPACE/sepdpc
   
    - name: Validate Repo
      run: |
        sepdpc validate $GITHUB_WORKSPACE
    
    - name: Publish Repo
      run: |
        sepdpc publish $GITHUB_WORKSPACE
